logo:  # add logo name
title: Nyah Way
description: > # this means to ignore newlines until "baseurl:"
  Nyah is a computer science student at the University of Toronto Scarborough. She is currently pursuing an Undergraduate degree in computer science entrepreneurship. This site hosts some of her projects.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: https://nyw8.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Nyah Way # add banner title
banner-desc: And still, I rise. - Maya Angelou

# Author settings
author-pic: nyah.png # your photo
author-name: Nyah Way # your name
about-author: Computer science specialist graduate from the University of Toronto Scarborough, now pursuing her full-time career at Google. # about author
email:
phone:
website: https://nyw8.github.io # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link
linkedin_url: https://www.linkedin.com/in/nyah-way/
github_url:   https://github.com/NyW8

# Disqus
discus_identifier: # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 1
paginate_path: /projects/page:num/

# Build settings
markdown: CommonMarkGhPages #kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
